import "@/styles/globals.css";


export const metadata = {
  title: '[/dev/arghya-sarkar/]',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div id="landing-wrapper"></div>
        {children}

        </body>
    </html>
  )
}
